name: taxi_client_app
description: Taxi MVP client app scaffold
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_map: ^7.0.2
  geolocator: ^13.0.2
  http: ^1.2.2
  latlong2: ^0.9.1
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.2
  flutter_map_dragmarker: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
